// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/alfakR.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_karyotype_abm
Rcpp::List run_karyotype_abm(Rcpp::List initial_population_r, Rcpp::List fitness_map_r, double p_missegregation, double dt, int n_steps, long long max_population_size, double culling_survival_fraction, int record_interval, int seed, Rcpp::NumericMatrix grf_centroids, double grf_lambda);
RcppExport SEXP _alfakR_run_karyotype_abm(SEXP initial_population_rSEXP, SEXP fitness_map_rSEXP, SEXP p_missegregationSEXP, SEXP dtSEXP, SEXP n_stepsSEXP, SEXP max_population_sizeSEXP, SEXP culling_survival_fractionSEXP, SEXP record_intervalSEXP, SEXP seedSEXP, SEXP grf_centroidsSEXP, SEXP grf_lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type initial_population_r(initial_population_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type fitness_map_r(fitness_map_rSEXP);
    Rcpp::traits::input_parameter< double >::type p_missegregation(p_missegregationSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< long long >::type max_population_size(max_population_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type culling_survival_fraction(culling_survival_fractionSEXP);
    Rcpp::traits::input_parameter< int >::type record_interval(record_intervalSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type grf_centroids(grf_centroidsSEXP);
    Rcpp::traits::input_parameter< double >::type grf_lambda(grf_lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(run_karyotype_abm(initial_population_r, fitness_map_r, p_missegregation, dt, n_steps, max_population_size, culling_survival_fraction, record_interval, seed, grf_centroids, grf_lambda));
    return rcpp_result_gen;
END_RCPP
}
// run_transition_treatment_abm
Rcpp::List run_transition_treatment_abm(Rcpp::List initial_population_r, Rcpp::List untreated_fitness_map_r, Rcpp::List treated_fitness_map_r, Rcpp::List adjacency_r, Rcpp::CharacterVector transition_karyotypes_r, double p_missegregation, double base_death_rate, double base_birth_rate, double fitness_birth_scale, double second_treatment_strength, int tau1_step, double dt, int n_steps, int record_interval, int seed);
RcppExport SEXP _alfakR_run_transition_treatment_abm(SEXP initial_population_rSEXP, SEXP untreated_fitness_map_rSEXP, SEXP treated_fitness_map_rSEXP, SEXP adjacency_rSEXP, SEXP transition_karyotypes_rSEXP, SEXP p_missegregationSEXP, SEXP base_death_rateSEXP, SEXP base_birth_rateSEXP, SEXP fitness_birth_scaleSEXP, SEXP second_treatment_strengthSEXP, SEXP tau1_stepSEXP, SEXP dtSEXP, SEXP n_stepsSEXP, SEXP record_intervalSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type initial_population_r(initial_population_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type untreated_fitness_map_r(untreated_fitness_map_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type treated_fitness_map_r(treated_fitness_map_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type adjacency_r(adjacency_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type transition_karyotypes_r(transition_karyotypes_rSEXP);
    Rcpp::traits::input_parameter< double >::type p_missegregation(p_missegregationSEXP);
    Rcpp::traits::input_parameter< double >::type base_death_rate(base_death_rateSEXP);
    Rcpp::traits::input_parameter< double >::type base_birth_rate(base_birth_rateSEXP);
    Rcpp::traits::input_parameter< double >::type fitness_birth_scale(fitness_birth_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type second_treatment_strength(second_treatment_strengthSEXP);
    Rcpp::traits::input_parameter< int >::type tau1_step(tau1_stepSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type record_interval(record_intervalSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_transition_treatment_abm(initial_population_r, untreated_fitness_map_r, treated_fitness_map_r, adjacency_r, transition_karyotypes_r, p_missegregation, base_death_rate, base_birth_rate, fitness_birth_scale, second_treatment_strength, tau1_step, dt, n_steps, record_interval, seed));
    return rcpp_result_gen;
END_RCPP
}
// alfak_project_forward_log_cpp
Rcpp::NumericMatrix alfak_project_forward_log_cpp(Rcpp::NumericVector x0, Rcpp::NumericVector f, Rcpp::NumericVector timepoints);
RcppExport SEXP _alfakR_alfak_project_forward_log_cpp(SEXP x0SEXP, SEXP fSEXP, SEXP timepointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type timepoints(timepointsSEXP);
    rcpp_result_gen = Rcpp::wrap(alfak_project_forward_log_cpp(x0, f, timepoints));
    return rcpp_result_gen;
END_RCPP
}
// alfak_neg_log_lik_cpp
double alfak_neg_log_lik_cpp(Rcpp::NumericVector param, Rcpp::NumericMatrix counts, Rcpp::NumericVector timepoints);
RcppExport SEXP _alfakR_alfak_neg_log_lik_cpp(SEXP paramSEXP, SEXP countsSEXP, SEXP timepointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type timepoints(timepointsSEXP);
    rcpp_result_gen = Rcpp::wrap(alfak_neg_log_lik_cpp(param, counts, timepoints));
    return rcpp_result_gen;
END_RCPP
}
// alfak_neighbor_objective_cpp
double alfak_neighbor_objective_cpp(double fc_param, Rcpp::NumericVector parent_fitness, Rcpp::NumericVector pij_values, Rcpp::NumericVector parent_birth_times, Rcpp::NumericVector timepoints, Rcpp::NumericMatrix parent_xfit, Rcpp::NumericVector child_obs, Rcpp::NumericVector ntot, double parent_fitness_mean, double prior_mean, double prior_sd, bool do_prior, double tol);
RcppExport SEXP _alfakR_alfak_neighbor_objective_cpp(SEXP fc_paramSEXP, SEXP parent_fitnessSEXP, SEXP pij_valuesSEXP, SEXP parent_birth_timesSEXP, SEXP timepointsSEXP, SEXP parent_xfitSEXP, SEXP child_obsSEXP, SEXP ntotSEXP, SEXP parent_fitness_meanSEXP, SEXP prior_meanSEXP, SEXP prior_sdSEXP, SEXP do_priorSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type fc_param(fc_paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parent_fitness(parent_fitnessSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pij_values(pij_valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parent_birth_times(parent_birth_timesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type timepoints(timepointsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type parent_xfit(parent_xfitSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type child_obs(child_obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ntot(ntotSEXP);
    Rcpp::traits::input_parameter< double >::type parent_fitness_mean(parent_fitness_meanSEXP);
    Rcpp::traits::input_parameter< double >::type prior_mean(prior_meanSEXP);
    Rcpp::traits::input_parameter< double >::type prior_sd(prior_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type do_prior(do_priorSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(alfak_neighbor_objective_cpp(fc_param, parent_fitness, pij_values, parent_birth_times, timepoints, parent_xfit, child_obs, ntot, parent_fitness_mean, prior_mean, prior_sd, do_prior, tol));
    return rcpp_result_gen;
END_RCPP
}
// alfak_qr_accum_cpp
Rcpp::List alfak_qr_accum_cpp(Rcpp::NumericMatrix x_trim, Rcpp::NumericMatrix dx_dt);
RcppExport SEXP _alfakR_alfak_qr_accum_cpp(SEXP x_trimSEXP, SEXP dx_dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x_trim(x_trimSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dx_dt(dx_dtSEXP);
    rcpp_result_gen = Rcpp::wrap(alfak_qr_accum_cpp(x_trim, dx_dt));
    return rcpp_result_gen;
END_RCPP
}
// pij_cpp
double pij_cpp(int i, int j, double beta);
static SEXP _alfakR_pij_cpp_try(SEXP iSEXP, SEXP jSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(pij_cpp(i, j, beta));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _alfakR_pij_cpp(SEXP iSEXP, SEXP jSEXP, SEXP betaSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_alfakR_pij_cpp_try(iSEXP, jSEXP, betaSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// get_A_inputs
List get_A_inputs(CharacterVector k_str, double beta, Nullable<double> Nmax_);
static SEXP _alfakR_get_A_inputs_try(SEXP k_strSEXP, SEXP betaSEXP, SEXP Nmax_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type k_str(k_strSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type Nmax_(Nmax_SEXP);
    rcpp_result_gen = Rcpp::wrap(get_A_inputs(k_str, beta, Nmax_));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _alfakR_get_A_inputs(SEXP k_strSEXP, SEXP betaSEXP, SEXP Nmax_SEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_alfakR_get_A_inputs_try(k_strSEXP, betaSEXP, Nmax_SEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// chrmod_cpp
List chrmod_cpp(double time, NumericVector state, List parms);
static SEXP _alfakR_chrmod_cpp_try(SEXP timeSEXP, SEXP stateSEXP, SEXP parmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type state(stateSEXP);
    Rcpp::traits::input_parameter< List >::type parms(parmsSEXP);
    rcpp_result_gen = Rcpp::wrap(chrmod_cpp(time, state, parms));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _alfakR_chrmod_cpp(SEXP timeSEXP, SEXP stateSEXP, SEXP parmsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_alfakR_chrmod_cpp_try(timeSEXP, stateSEXP, parmsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// chrmod_rel_cpp
List chrmod_rel_cpp(double time, NumericVector x, List parms);
static SEXP _alfakR_chrmod_rel_cpp_try(SEXP timeSEXP, SEXP xSEXP, SEXP parmsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type parms(parmsSEXP);
    rcpp_result_gen = Rcpp::wrap(chrmod_rel_cpp(time, x, parms));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _alfakR_chrmod_rel_cpp(SEXP timeSEXP, SEXP xSEXP, SEXP parmsSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_alfakR_chrmod_rel_cpp_try(timeSEXP, xSEXP, parmsSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _alfakR_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("double(*pij_cpp)(int,int,double)");
        signatures.insert("List(*get_A_inputs)(CharacterVector,double,Nullable<double>)");
        signatures.insert("List(*chrmod_cpp)(double,NumericVector,List)");
        signatures.insert("List(*chrmod_rel_cpp)(double,NumericVector,List)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _alfakR_RcppExport_registerCCallable() { 
    R_RegisterCCallable("alfakR", "_alfakR_pij_cpp", (DL_FUNC)_alfakR_pij_cpp_try);
    R_RegisterCCallable("alfakR", "_alfakR_get_A_inputs", (DL_FUNC)_alfakR_get_A_inputs_try);
    R_RegisterCCallable("alfakR", "_alfakR_chrmod_cpp", (DL_FUNC)_alfakR_chrmod_cpp_try);
    R_RegisterCCallable("alfakR", "_alfakR_chrmod_rel_cpp", (DL_FUNC)_alfakR_chrmod_rel_cpp_try);
    R_RegisterCCallable("alfakR", "_alfakR_RcppExport_validate", (DL_FUNC)_alfakR_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_alfakR_run_karyotype_abm", (DL_FUNC) &_alfakR_run_karyotype_abm, 11},
    {"_alfakR_run_transition_treatment_abm", (DL_FUNC) &_alfakR_run_transition_treatment_abm, 15},
    {"_alfakR_alfak_project_forward_log_cpp", (DL_FUNC) &_alfakR_alfak_project_forward_log_cpp, 3},
    {"_alfakR_alfak_neg_log_lik_cpp", (DL_FUNC) &_alfakR_alfak_neg_log_lik_cpp, 3},
    {"_alfakR_alfak_neighbor_objective_cpp", (DL_FUNC) &_alfakR_alfak_neighbor_objective_cpp, 13},
    {"_alfakR_alfak_qr_accum_cpp", (DL_FUNC) &_alfakR_alfak_qr_accum_cpp, 2},
    {"_alfakR_pij_cpp", (DL_FUNC) &_alfakR_pij_cpp, 3},
    {"_alfakR_get_A_inputs", (DL_FUNC) &_alfakR_get_A_inputs, 3},
    {"_alfakR_chrmod_cpp", (DL_FUNC) &_alfakR_chrmod_cpp, 3},
    {"_alfakR_chrmod_rel_cpp", (DL_FUNC) &_alfakR_chrmod_rel_cpp, 3},
    {"_alfakR_RcppExport_registerCCallable", (DL_FUNC) &_alfakR_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_alfakR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
